### ISSUE TITLE
Hi thinmartian

### ISSUE THREAD

**Issue by jota-xx** [thinmartian/cms#1]
I do not have good English. Sorry.
I am using CMS, as I get the list of images of an object.

.yaml setting ==> 
photo:
        type: "media"
        label: "Seleccione una foto"
        allowed:
            - image
        limit: 1

my blade ==> {{ $object->photo }} no working, {{ $object->photo[0] }} no working, {{ $object->media }} no working,
Help! thanks.

**Comment by de-monkeyz** [comment]
Hi there!

Thanks for showing interest in the project. Documentation is not the best at the moment, but I appreciate you giving it a go. You'll need to access the media relation as you showed in your last example, however you'll need to additionally call it as a function using the relationship name ("photo") in your example.

```php
$object->media("photo")->first()
```

That will get you the media object for your code. If you need to get a quick URL (and resize the image) you can use the CmsImage service:

```php
CmsImage::get($object->media("photo")->first()->id, $width, $height)
```

Sorry for the really complicated way that this works, it's definitely a part of the system I would like to streamline and optimise in future.

**Comment by jota-xx** [comment]
Thank!!!
New question:!!! jajja
To create a dynamic select, how to load the combo from the bbdd?
.yaml ==> 
    category:
        type: "select"
        label: "Categoria"
        persist: true
        validationOnCreate: "required"
        validationOnUpdate: "required"
        options:
            latest: "Latest News"
            archive: "Archive"

How can I make dynamic choices?

sorry my english

**Comment by de-monkeyz** [comment]
You should just be able to follow the documentation for relationships in that case: https://github.com/thinmartian/cms#relationships

I'm assuming you have another model for Categories here. 

```yaml
relations:
  category:
    type: 'belongsTo'
fields:
  category_id: # singular name
    type: "relation"
    label: "Category"
    persist: true
    relationType: 'belongsTo'
    className: 'category' # optional: classname related to this model e.g if the class is CmsAuthor you can put 'author'
    relationField: 'name' # optional: name of field to show in dropdown stuff
```

As of right now we don't support dynamic drop downs via non-relational data.
